language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
  - sudo apt-get update -y
  - sudo apt-get install mosquitto -y
  - sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
  - sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
